/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedMijnRoutesRouteImport } from './routes/_authenticated/mijn-routes'
import { Route as AuthenticatedMeldingenRouteImport } from './routes/_authenticated/meldingen'
import { Route as AuthenticatedEigenarenRouteImport } from './routes/_authenticated/eigenaren'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMijnRoutesRoute = AuthenticatedMijnRoutesRouteImport.update({
  id: '/mijn-routes',
  path: '/mijn-routes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeldingenRoute = AuthenticatedMeldingenRouteImport.update({
  id: '/meldingen',
  path: '/meldingen',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEigenarenRoute = AuthenticatedEigenarenRouteImport.update({
  id: '/eigenaren',
  path: '/eigenaren',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/eigenaren': typeof AuthenticatedEigenarenRoute
  '/meldingen': typeof AuthenticatedMeldingenRoute
  '/mijn-routes': typeof AuthenticatedMijnRoutesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/eigenaren': typeof AuthenticatedEigenarenRoute
  '/meldingen': typeof AuthenticatedMeldingenRoute
  '/mijn-routes': typeof AuthenticatedMijnRoutesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/eigenaren': typeof AuthenticatedEigenarenRoute
  '/_authenticated/meldingen': typeof AuthenticatedMeldingenRoute
  '/_authenticated/mijn-routes': typeof AuthenticatedMijnRoutesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/eigenaren'
    | '/meldingen'
    | '/mijn-routes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/admin' | '/eigenaren' | '/meldingen' | '/mijn-routes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/eigenaren'
    | '/_authenticated/meldingen'
    | '/_authenticated/mijn-routes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/mijn-routes': {
      id: '/_authenticated/mijn-routes'
      path: '/mijn-routes'
      fullPath: '/mijn-routes'
      preLoaderRoute: typeof AuthenticatedMijnRoutesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meldingen': {
      id: '/_authenticated/meldingen'
      path: '/meldingen'
      fullPath: '/meldingen'
      preLoaderRoute: typeof AuthenticatedMeldingenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/eigenaren': {
      id: '/_authenticated/eigenaren'
      path: '/eigenaren'
      fullPath: '/eigenaren'
      preLoaderRoute: typeof AuthenticatedEigenarenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedEigenarenRoute: typeof AuthenticatedEigenarenRoute
  AuthenticatedMeldingenRoute: typeof AuthenticatedMeldingenRoute
  AuthenticatedMijnRoutesRoute: typeof AuthenticatedMijnRoutesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedEigenarenRoute: AuthenticatedEigenarenRoute,
  AuthenticatedMeldingenRoute: AuthenticatedMeldingenRoute,
  AuthenticatedMijnRoutesRoute: AuthenticatedMijnRoutesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
