/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GedeeldTokenRouteImport } from './routes/gedeeld.$token'
import { Route as AuthenticatedWijzigingenRouteImport } from './routes/_authenticated/wijzigingen'
import { Route as AuthenticatedVoertuigenRouteImport } from './routes/_authenticated/voertuigen'
import { Route as AuthenticatedTalenRouteImport } from './routes/_authenticated/talen'
import { Route as AuthenticatedMijnRoutesRouteImport } from './routes/_authenticated/mijn-routes'
import { Route as AuthenticatedMijnMeldingenRouteImport } from './routes/_authenticated/mijn-meldingen'
import { Route as AuthenticatedMeldingenRouteImport } from './routes/_authenticated/meldingen'
import { Route as AuthenticatedGebruikersRouteImport } from './routes/_authenticated/gebruikers'
import { Route as AuthenticatedEigenarenRouteImport } from './routes/_authenticated/eigenaren'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GedeeldTokenRoute = GedeeldTokenRouteImport.update({
  id: '/gedeeld/$token',
  path: '/gedeeld/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWijzigingenRoute =
  AuthenticatedWijzigingenRouteImport.update({
    id: '/wijzigingen',
    path: '/wijzigingen',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVoertuigenRoute = AuthenticatedVoertuigenRouteImport.update({
  id: '/voertuigen',
  path: '/voertuigen',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTalenRoute = AuthenticatedTalenRouteImport.update({
  id: '/talen',
  path: '/talen',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMijnRoutesRoute = AuthenticatedMijnRoutesRouteImport.update({
  id: '/mijn-routes',
  path: '/mijn-routes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMijnMeldingenRoute =
  AuthenticatedMijnMeldingenRouteImport.update({
    id: '/mijn-meldingen',
    path: '/mijn-meldingen',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeldingenRoute = AuthenticatedMeldingenRouteImport.update({
  id: '/meldingen',
  path: '/meldingen',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGebruikersRoute = AuthenticatedGebruikersRouteImport.update({
  id: '/gebruikers',
  path: '/gebruikers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEigenarenRoute = AuthenticatedEigenarenRouteImport.update({
  id: '/eigenaren',
  path: '/eigenaren',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/eigenaren': typeof AuthenticatedEigenarenRoute
  '/gebruikers': typeof AuthenticatedGebruikersRoute
  '/meldingen': typeof AuthenticatedMeldingenRoute
  '/mijn-meldingen': typeof AuthenticatedMijnMeldingenRoute
  '/mijn-routes': typeof AuthenticatedMijnRoutesRoute
  '/talen': typeof AuthenticatedTalenRoute
  '/voertuigen': typeof AuthenticatedVoertuigenRoute
  '/wijzigingen': typeof AuthenticatedWijzigingenRoute
  '/gedeeld/$token': typeof GedeeldTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/eigenaren': typeof AuthenticatedEigenarenRoute
  '/gebruikers': typeof AuthenticatedGebruikersRoute
  '/meldingen': typeof AuthenticatedMeldingenRoute
  '/mijn-meldingen': typeof AuthenticatedMijnMeldingenRoute
  '/mijn-routes': typeof AuthenticatedMijnRoutesRoute
  '/talen': typeof AuthenticatedTalenRoute
  '/voertuigen': typeof AuthenticatedVoertuigenRoute
  '/wijzigingen': typeof AuthenticatedWijzigingenRoute
  '/gedeeld/$token': typeof GedeeldTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/eigenaren': typeof AuthenticatedEigenarenRoute
  '/_authenticated/gebruikers': typeof AuthenticatedGebruikersRoute
  '/_authenticated/meldingen': typeof AuthenticatedMeldingenRoute
  '/_authenticated/mijn-meldingen': typeof AuthenticatedMijnMeldingenRoute
  '/_authenticated/mijn-routes': typeof AuthenticatedMijnRoutesRoute
  '/_authenticated/talen': typeof AuthenticatedTalenRoute
  '/_authenticated/voertuigen': typeof AuthenticatedVoertuigenRoute
  '/_authenticated/wijzigingen': typeof AuthenticatedWijzigingenRoute
  '/gedeeld/$token': typeof GedeeldTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/eigenaren'
    | '/gebruikers'
    | '/meldingen'
    | '/mijn-meldingen'
    | '/mijn-routes'
    | '/talen'
    | '/voertuigen'
    | '/wijzigingen'
    | '/gedeeld/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/eigenaren'
    | '/gebruikers'
    | '/meldingen'
    | '/mijn-meldingen'
    | '/mijn-routes'
    | '/talen'
    | '/voertuigen'
    | '/wijzigingen'
    | '/gedeeld/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/eigenaren'
    | '/_authenticated/gebruikers'
    | '/_authenticated/meldingen'
    | '/_authenticated/mijn-meldingen'
    | '/_authenticated/mijn-routes'
    | '/_authenticated/talen'
    | '/_authenticated/voertuigen'
    | '/_authenticated/wijzigingen'
    | '/gedeeld/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  GedeeldTokenRoute: typeof GedeeldTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gedeeld/$token': {
      id: '/gedeeld/$token'
      path: '/gedeeld/$token'
      fullPath: '/gedeeld/$token'
      preLoaderRoute: typeof GedeeldTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wijzigingen': {
      id: '/_authenticated/wijzigingen'
      path: '/wijzigingen'
      fullPath: '/wijzigingen'
      preLoaderRoute: typeof AuthenticatedWijzigingenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/voertuigen': {
      id: '/_authenticated/voertuigen'
      path: '/voertuigen'
      fullPath: '/voertuigen'
      preLoaderRoute: typeof AuthenticatedVoertuigenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/talen': {
      id: '/_authenticated/talen'
      path: '/talen'
      fullPath: '/talen'
      preLoaderRoute: typeof AuthenticatedTalenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mijn-routes': {
      id: '/_authenticated/mijn-routes'
      path: '/mijn-routes'
      fullPath: '/mijn-routes'
      preLoaderRoute: typeof AuthenticatedMijnRoutesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mijn-meldingen': {
      id: '/_authenticated/mijn-meldingen'
      path: '/mijn-meldingen'
      fullPath: '/mijn-meldingen'
      preLoaderRoute: typeof AuthenticatedMijnMeldingenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meldingen': {
      id: '/_authenticated/meldingen'
      path: '/meldingen'
      fullPath: '/meldingen'
      preLoaderRoute: typeof AuthenticatedMeldingenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gebruikers': {
      id: '/_authenticated/gebruikers'
      path: '/gebruikers'
      fullPath: '/gebruikers'
      preLoaderRoute: typeof AuthenticatedGebruikersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/eigenaren': {
      id: '/_authenticated/eigenaren'
      path: '/eigenaren'
      fullPath: '/eigenaren'
      preLoaderRoute: typeof AuthenticatedEigenarenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedEigenarenRoute: typeof AuthenticatedEigenarenRoute
  AuthenticatedGebruikersRoute: typeof AuthenticatedGebruikersRoute
  AuthenticatedMeldingenRoute: typeof AuthenticatedMeldingenRoute
  AuthenticatedMijnMeldingenRoute: typeof AuthenticatedMijnMeldingenRoute
  AuthenticatedMijnRoutesRoute: typeof AuthenticatedMijnRoutesRoute
  AuthenticatedTalenRoute: typeof AuthenticatedTalenRoute
  AuthenticatedVoertuigenRoute: typeof AuthenticatedVoertuigenRoute
  AuthenticatedWijzigingenRoute: typeof AuthenticatedWijzigingenRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedEigenarenRoute: AuthenticatedEigenarenRoute,
  AuthenticatedGebruikersRoute: AuthenticatedGebruikersRoute,
  AuthenticatedMeldingenRoute: AuthenticatedMeldingenRoute,
  AuthenticatedMijnMeldingenRoute: AuthenticatedMijnMeldingenRoute,
  AuthenticatedMijnRoutesRoute: AuthenticatedMijnRoutesRoute,
  AuthenticatedTalenRoute: AuthenticatedTalenRoute,
  AuthenticatedVoertuigenRoute: AuthenticatedVoertuigenRoute,
  AuthenticatedWijzigingenRoute: AuthenticatedWijzigingenRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  GedeeldTokenRoute: GedeeldTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
